import math
def assert_store_response(page,pageSize,body: dict):
    assert "data" in body, "Response should contain 'data' field"
    assert isinstance(body["data"], list), "'data' field should be a list"
    for item in body["data"]:
        assert "id" in item, "Each menu item should contain 'id'"
        assert "mexchangeStoreId" in item, "Each menu item should contain 'mexchangeStoreId'"
        assert "name" in item, "Each menu item should contain 'name'"
        assert "mexchangePartnerId" in item, "Each menu item should contain 'address'"
        assert "partnerId" in item, "Each menu item should contain 'latitude'"
        assert "merchantId" in item, "Each menu item should contain 'longitude'"
        assert "total" in body, "Response should contain 'total' field"
        assert "page" in body, "Response should contain 'page' field"
        assert body["page"] == page, f"Expected page {page}, got {body['page']}"
        assert "pageSize" in body, "Response should contain 'pageSize' field"
        assert body["pageSize"] == pageSize, f"Expected pageSize {pageSize}, got {body['pageSize']}"
        assert "totalPages" in body, "Response should contain 'totalPages' field"
        assert len(body["data"]) <= pageSize, f"Expected at most {pageSize} items in data, got {len(body['data'])}"
        assert body["page"] <= body["totalPages"], f"Expected page {body['page']} to be less than or equal to totalPages {body['totalPages']}"
        assert body["totalPages"] == math.ceil(body["total"] / pageSize), f"Expected totalPages {math.ceil(body['total'] / pageSize)}, got {body['totalPages']}"